//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanTinDuBao
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BanTinDuBao()
        {
            this.TepBanTinDinhKems = new HashSet<TepBanTinDinhKem>();
        }
    
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public string TomTatNoiDung { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayThucHien { get; set; }
        public Nullable<int> MaLoaiBanTin { get; set; }
        public Nullable<int> MaKVHC { get; set; }
        public string MoTaViTri { get; set; }
        public Nullable<int> MaKhuVuc { get; set; }
        public Nullable<int> ThoiGianDuBao { get; set; }
        public Nullable<int> MaCapDoDuBao { get; set; }
        public string TenToChucDuBao { get; set; }
        public Nullable<int> MaLoaiThienTai { get; set; }
        public Nullable<bool> TrangThaiDuyet { get; set; }
        public bool BanTin_Status { get; set; }
        public string NguoiDang { get; set; }
        public string NguonTinDuBao { get; set; }
        public bool IsDeleted { get; set; }
        public string KEY_SEARCH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TepBanTinDinhKem> TepBanTinDinhKems { get; set; }
        public virtual KhuVuc KhuVuc { get; set; }
    }
}
