//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonViToChuc
    {
        public int ID { get; set; }
        public string TenDonVi { get; set; }
        public string DiaChi { get; set; }
        public string MaSoThue { get; set; }
        public bool IsDeleted { get; set; }
        public string ToaDoX { get; set; }
        public string ToaDoY { get; set; }
    }
}
