//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiBanTin
    {
        public int ID { get; set; }
        public string TenLoaiBanTin { get; set; }
        public Nullable<int> MaThanhPhanDuBao { get; set; }
        public string MoTa { get; set; }
        public bool IsDeleted { get; set; }
    }
}
