//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhimHinhAnh
    {
        public int ID { get; set; }
        public string TieuDe { get; set; }
        public Nullable<System.DateTime> NgayThang { get; set; }
        public string TenTapTin { get; set; }
        public string DuongDanURL { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> ThoiGianCapNhat { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsVideo { get; set; }
        public bool IsImage { get; set; }
    }
}
