//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TESTEntities : DbContext
    {
        public TESTEntities()
            : base("name=TESTEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees1> Employees1 { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<CompanyST> CompanySTs { get; set; }
        public virtual DbSet<BanDo> BanDoes { get; set; }
        public virtual DbSet<PhimHinhAnh> PhimHinhAnhs { get; set; }
        public virtual DbSet<FileDinhKem> FileDinhKems { get; set; }
        public virtual DbSet<BanTinDuBao> BanTinDuBaos { get; set; }
        public virtual DbSet<TepBanTinDinhKem> TepBanTinDinhKems { get; set; }
        public virtual DbSet<ThongTinGiayPhep> ThongTinGiayPheps { get; set; }
        public virtual DbSet<KhuVuc> KhuVucs { get; set; }
        public virtual DbSet<LoaiBanTin> LoaiBanTins { get; set; }
        public virtual DbSet<LoaiThienTai> LoaiThienTais { get; set; }
        public virtual DbSet<CapDo> CapDoes { get; set; }
        public virtual DbSet<KhuVucHanhChinh> KhuVucHanhChinhs { get; set; }
        public virtual DbSet<DonViToChuc> DonViToChucs { get; set; }
    }
}
