//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TEST.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongTinGiayPhep
    {
        public int ID { get; set; }
        public string SoHieu { get; set; }
        public string Nam { get; set; }
        public Nullable<System.DateTime> NgayThang { get; set; }
        public string TenDonVi { get; set; }
        public string PhamViHoatDong { get; set; }
        public Nullable<int> DoiTuongCungCap { get; set; }
        public string GiaHan { get; set; }
        public Nullable<int> DonViKyXacNhan { get; set; }
        public Nullable<int> MaCapDoDuBao { get; set; }
        public string TrangThaiGiayPhep { get; set; }
        public string LyDoThuHoi { get; set; }
        public bool IsDeleted { get; set; }
    }
}
